######################## Master configuration ############################

# This is the master configuration file which contains the configuration 
# source definitions.
#
# You can find the full configuration reference here:
# <Update documentation link, tech community article link>

#=======================  Sources configuration ==========================

sources:

#--------------------- YAML file configuration source --------------------

- type: YAML
  allowEdit: true
  properties:
    location: system-settings.yml

#------------------- Properties file configuration source ----------------

- type: PROPERTIES
  allowEdit: true
  properties:
    location: system-settings.properties
#

#==================================  END =================================
